services:
  backend:
    build:
      context: .
      dockerfile: DockerFile
    expose:
      - "5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
